title: minima
author: Dodoza1415
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first site : from dodoza 

# social links
twitter_username: dodoza1415 # DO NOT include the @ character, or else the build will fail!
github_username:  dodoza1415 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
